before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document epub-parser epub-maker rouge rouge-lexers-fluentd optparse-pathname colored gettext rake test-unit test-unit-notify simplecov rubygems-tasks yard pry pry-doc zipruby asciidoctor

test:2.2:
  image: ruby:2.2
  script: rake test
  except:
    - tags
  cache:
    key: ruby:2.3
    paths:
      - deps

test:2.3:
  image: ruby:2.3
  script: rake test
  except:
    - tags
  cache:
    key: ruby:2.3
    paths:
      - deps

test:2.4:
  image: ruby:2.4
  script: rake test
  except:
    - tags
  cache:
    key: ruby:2.4
    paths:
      - deps

test:2.5:
  image: ruby:2.5
  script: rake test
  except:
    - tags
  cache:
    key: ruby:2.5
    paths:
      - deps

test:2.6:
  image: ruby:2.6
  script: rake test
  except:
    - tags
  cache:
    key: ruby:2.6
    paths:
      - deps

test:2.7:
  image: ruby:2.7
  script: rake test
  except:
    - tags
  cache:
    key: ruby:2.7
    paths:
      - deps
