before_script:
  - ruby -v
  - which ruby
  - bundle install

test:2.7:
  image: ruby:2.7
  script: rake test
  except:
    - tags
  cache:
    key: ruby:2.7
    paths:
      - deps

test:3.0:
  image: ruby:3.0
  script: rake test
  except:
    - tags
  cache:
    key: ruby:3.0
    paths:
      - deps

test:3.1:
  image: ruby:3.1
  script: rake test
  except:
    - tags
  cache:
    key: ruby:3.1
    paths:
      - deps

test:3.2:
  image: ruby:3.2
  script: rake test
  except:
    - tags
  cache:
    key: ruby:3.2
    paths:
      - deps

test:3.3:
  image: ruby:3.3
  script: rake test
  except:
    - tags
  cache:
    key: ruby:3.3
    paths:
      - deps

test:3.4:
  image: ruby:3.4
  script: rake test
  except:
    - tags
  cache:
    key: ruby:3.4
    paths:
      - deps
